### PR TITLE
Hotfix/crumbissuer

### PR DESCRIPTION
**Pull request by hamaron**

### CODE REVIEW

**Comment by hamaron** [comment]
PR for #38

**Comment by ojacquemart** [comment]
:+1: 
It's maybe not a good practice to use e.printStackTrace?

**Comment by hamaron** [comment]
@ojacquemart I checked the use of ``` e.printStackTrace() ``` in the code base and I found a coupled of them used in ``` JenkindServer.java ``` at the time, so I decided to use the method.
But I agree to your point. Do you have any good ideas for this? or someone does?

**Comment by ojacquemart** [comment]
It's ok if it `printStackTrace` is already used in the codebase.

**Comment by pnathan** [comment]
Speaking as an occasional user, why wouldn't we want `printStackTrace()`, @ojacquemart ?

**Comment by ojacquemart** [comment]
By using a logging framework, you can log in different levels (trace, debug, info, warn, error, ...). Also, you can choose your output: file, console, ... and you can keep consistency in your logs format and so on. All that is often configurable through a file.

By the way, the PR is great and I am waiting for a merge :)

**Comment by hamaron** [comment]
Yup, I've been waiting for getting this PR merged for more than a year ;)

**Comment by khmarbaise** [comment]
First thanks for the PR, but can you please squash the commits...

**Comment by ojacquemart** [comment]
ping @hamaron  :)

**Comment by hamaron** [comment]
@ojacquemart Oops! I created another PR: #116 :)

**Pull request closed without merging**
