### PR TITLE
Added support to rename Jenkins jobs

### PR DESCRIPTION
**Pull request by jfisbein**
Added method renameJob to rename a job

### CODE REVIEW

**Comment by khmarbaise** [comment]
Can you please check why so many lines have changed in the change set...for added a single method ? line endings ?

**Comment by jfisbein** [comment]
Sorry the automatic code style from my IDE messed all, I just made a new version including only the new method.

**Comment by khmarbaise** [comment]
No problem. You have fixed and so i can simply merge it....

**Comment by jfisbein** [comment]
When is it planned to release v0.3.5?

**Comment by khmarbaise** [comment]
At the moment there is no plan about the time to release...is the a special reason why you are asking ?

**Comment by jfisbein** [comment]
Because I want to use the new rename feature :-)

**Pull request merged**
