### PR TITLE
Improved the integration test code.

### PR DESCRIPTION
**Pull request by khmarbaise**
Using scheduleBuild2(0,..).get() will return the resulting object incl. waiting for the end of the build which means no need for a while loop in the test cases to wait for the end of the scheduled builds.

### CODE REVIEW

**Comment by cosmin** [comment]
@khmarbaise thank you for your continued contributions to this project. I don't have as much time as I used to for responding to pull requests. I have given you commit rights so you can more easily contribute to the project. I am happy to answer questions or provide ideas if you need them, but I don't need to be a roadblock. Thanks

**Comment by khmarbaise** [comment]
Thanks @cosmin.

**Comment by khmarbaise** [comment]
I have tried to push to RisingOak/jenkins-client which unfortunately didn't work. Can you check the permissions ? Or do i need to do something?

**Comment by cosmin** [comment]
Looks like I forgot to apply all the changes. Try again

**Pull request merged**
