### PR TITLE
#39: Don't propagate IOException when GET for /CrumbIssuer fails.

### PR DESCRIPTION
**Pull request by hamaron**

### CODE REVIEW

**Comment by cosmin** [comment]
this no longer merges cleanly

**Comment by hamaron** [comment]
Hi, cosmin!
If this patch is acceptable with/without any modifications, please let me know.
I will rebase this branch on the latest master branch.

Thank you! :)

**Comment by zjs** [comment]
What's the status of this? Do we just need an updated version of this patch?

**Comment by khmarbaise** [comment]
Would you please so kind and rebase this PR to the current state of the master code and squash if not already done. Thanks for your support.

**Comment by ojacquemart** [comment]
The javadoc says that the getQuietly logs the error and does not propagate the IOException but it throws an Assertion error.

Should the method just log the IOException & return a null value instead?

I could submit a new PR if anyone is interested. I had to make this change to use the library in a project.

**Comment by hamaron** [comment]
Oh sorry that I didn't realize I had your comments. 
I can clean up the code as you suggested. please wait a sec.

**Comment by hamaron** [comment]
I will create another PR, hence this PR was closed.

**Comment by hamaron** [comment]
Created a new PR #109.
@khmarbaise Could you have a  quick look and merge it if it looks good to you?

**Pull request closed without merging**
