### PR TITLE
 #39: Don't propagate IOException when GET for /CrumbIssuer fails.

### PR DESCRIPTION
**Pull request by hamaron**
Squashed the commits in #110

### CODE REVIEW

**Comment by hamaron** [comment]
@ojacquemart @khmarbaise Sorry for keeping you waiting!

**Comment by ojacquemart** [comment]
Any news on this PR merge? :)

**Comment by hamaron** [comment]
@khmarbaise bump. could you take a look at this PR?

**Comment by hamaron** [comment]
@khmarbaise Thanks! :)

**Comment by ojacquemart** [comment]
Thanks :+1: 

Any idea of when the 0.3.3 will be released?

**Pull request merged**
