### PR TITLE
Feature/jarjar

### PR DESCRIPTION
**Pull request by terabyte**
This would solve #75.  Creating this PR to discuss if this is ok as-is or if we need to make the jar-jar-ing conditional or something.  Or you might rightfully ask me to clean up my snarky comments =)  Let me know what changes if any you'd like before merging.

### CODE REVIEW

**Comment by cosmin** [comment]
Let's change the target package to the group id of this project plus com.google.common.* 

Also, change to comment to be a little less snarky :)

**Comment by terabyte** [comment]
Thanks guys!

**Comment by khmarbaise** [comment]
Unfortunately i have checked the result of jarjar plugin which replaces the original artifact. I have to replace it with maven-shade-plugin cause with shade i can control if the original artifact is being replaced or not. In this case it makes sense to attach the special artifact which contains guava code as a supplemental artifact with a classifier (e.g. stash). What do you think ? Can someone check this?

**Comment by terabyte** [comment]
I'm fine with that solution, I'll try it out when I get a chance

**Pull request merged**
