### PR TITLE
replace DefaultHttpClient with HttpClientBuilder

### PR DESCRIPTION
**Pull request by mephi42**
DefaultHttpClient does not seem to work with SNI [1].

[1] http://en.wikipedia.org/wiki/Server_Name_Indication

### CODE REVIEW

**Comment by pnathan** [comment]
PR doesn't merge.

:+1:  for this PR though - I've had some nasty redirect loops from some URLs (i.e., preparing the master for shutdown) and I *think* the appropriate strategy is a LaxRedirectStrategy that the HttpClientBuilder supports.

**Comment by cosmin** [comment]
@pnathan I'll merge this in if someone can rebase this on latest master.

**Comment by khmarbaise** [comment]
Interests to rebase this branch to the current master state ?

**Comment by pnathan** [comment]
@khmarbaise  Let's see if I can take a swing at this (again - I muddled around a fair amount in May trying to get this rebased properly).

**Comment by pnathan** [comment]
@khmarbaise  - submitted #100 which rebases this patch in.

**Pull request merged**
